FiresportCalendar/Controllers/ManageRolesController.cs
using FiresportCalendar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
namespace FiresportCalendar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageRolesController : Controller
    {
        private readonly UserManager<Person> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;
        public ManageRolesController(UserManager<Person> userManager, RoleManager<IdentityRole> roleManager, IConfiguration configuration)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = _userManager.Users.OrderBy(u => u.UserName).ToList(); // Filtruje uživatele s potvrzeným emailem

            var userRoleViewModels = new List<UserRoleViewModel>();

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);

                userRoleViewModels.Add(new UserRoleViewModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    Email = user.Email,
                    UserRoles = roles.ToList(),
                    EmailConfirmed = user.EmailConfirmed
                });
            }
            ViewData["SuperAdminEmail"] = _configuration["SuperAdminEmail"];
            ViewBag.AllRoles = _roleManager.Roles.Select(r => r.Name).ToList();

            return View(userRoleViewModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ToggleRole(string userId, string roleName)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound("User not found.");
            }

            if(user.Email == _configuration["SuperAdminEmail"])
            {
                return NotFound("User not found.");
            }

            var roles = await _userManager.GetRolesAsync(user);
            if (roles.Contains(roleName))
            {
                await _userManager.RemoveFromRoleAsync(user, roleName); 
            }
            else
            {
                await _userManager.AddToRoleAsync(user, roleName);
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmUser(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound("User not found.");
            }

            user.EmailConfirmed = true;
            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                TempData["StatusMessage"] = "Uživatel byl úspěšně potvrzen";
            }
            else
            {
                TempData["StatusMessage"] = "Chyba při pokusu o potvrzení uživatele";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

FiresportCalendar/Views/ManageRoles/Index.cshtml
@model IEnumerable<UserRoleViewModel>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
   
        ViewData["Title"] = "Správa rolí";
    

    <div class="container mt-2">
        @if (TempData["StatusMessage"] != null)
        {
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                @TempData["StatusMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
        <h2 class="mb-4">Správa rolí</h2>

        @foreach (var user in Model.Where(u => u.EmailConfirmed))
        {
            <div class="row mb-3">
                <div class="col-3">
                    <strong>@user.UserName</strong>
                    <br>
                    <small>@user.Email</small>
                </div>

                <div class="col-9">
                    @foreach (var role in ViewBag.AllRoles)
                    {
                        var hasRole = user.UserRoles.Contains(role);

                        @if (user.UserName != User.Identity.Name && user.Email != ViewData["SuperAdminEmail"] as string)
                        {
                            <form method="post" action="@Url.Action("ToggleRole", "ManageRoles")" style="display:inline;">
                                @Html.AntiForgeryToken()
                                <input type="hidden" name="userId" value="@user.Id" />
                                <input type="hidden" name="roleName" value="@role" />
                                <button type="submit" class="btn @(hasRole ? "btn-primary" : "btn-outline-primary") btn-sm mx-1">
                                    @role
                                </button>
                            </form>
                        }
                        else
                        {
                            <!-- Pro uživatele, který je aktuálně přihlášen, nebude možnost měnit role -->
                            <button class="btn btn-secondary btn-sm mx-1" disabled>
                                @role
                            </button>
                        }
                    }
                </div>
            </div>
        }

        <h2 class="mt-4 mb-4">Nepotvrzení uživatelé</h2>

        @foreach (var user in Model.Where(u => !u.EmailConfirmed))
        {
            <div class="row mb-3">
                <div class="col-3">
                    <strong>@user.UserName</strong>
                    <br>
                    <small>@user.Email</small>
                </div>

                <div class="col-9">
               
                    <form method="post" action="@Url.Action("ConfirmUser", "ManageRoles")" style="display:inline;">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="userId" value="@user.Id" />
                        <button type="submit" class="btn btn-outline-primary btn-sm mx-1">
                            Potvrdit
                        </button>
                    </form>
                </div>
            </div>
        }
    </div>
}