FiresportCalendar/Models/Race.cs
using Microsoft.Identity.Client;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace FiresportCalendar.Models
{
    public class Race
    {
        public int Id { get; set; }
        [Display(Name = "Místo")]
        public string Place { get; set; } = string.Empty;
        [Display(Name = "Datum a čas")]
        public DateTime DateTime { get; set; }
        [Display(Name = "Časomíra?")]
        public bool Timer { get; set; } = false;
        [Display(Name = "Liga")]
        public int? LeagueId { get; set; }
        public League? League { get; set; }
        public List<TeamRace> TeamRaces { get; set; } = new List<TeamRace>();
    
    }
}

FiresportCalendar/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using FiresportCalendar.Models;
using Microsoft.AspNetCore.Authorization;
using FiresportCalendar.Services;
//using Microsoft.AspNetCore.Identity;

namespace FiresportCalendar.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RaceController : Controller
    {
        private readonly IRaceService _raceService;
        private readonly ILeagueService _leagueService;

        public RaceController(
            IRaceService raceService,
            ILeagueService leagueService)
        {
            _raceService = raceService;
            _leagueService = leagueService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _raceService.GetAllUpcomingRaces());
        }

        //GET: Races/Detail/5
        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            EventDetailModel model = new EventDetailModel();

            var race = await _raceService.GetRaceById(id.Value);
            if (race == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Races/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Leagues = await _leagueService.GetAllLeagues();
            return View();
        }

        // POST: Races/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Race race)
        {
            if (ModelState.IsValid)
            {
                await _raceService.AddRaceAsync(race);
                return RedirectToAction(nameof(Index));
            }
            return View(race);
        }

        // GET: Races/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _raceService.GetRaceById(id.Value);
            ViewBag.Leagues = await _leagueService.GetAllLeagues();
            if (race == null)
            {
                return NotFound();
            }
            return View(race);
        }

        // POST: Races/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Race race)
        {
            if (id != race.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _raceService.UpdateRaceAsync(race);
                }
                catch (Exception)
                {
                    if (!RaceExists(race.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Races/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _raceService.DeleteByIdAsync(id);

            return RedirectToAction(nameof(Index));
        }

        private bool RaceExists(int id)
        {
            return (_raceService.GetRaceById(id) == null) ? false : true ;
        }
        
    }
}

FiresportCalendar/Views/Race/Create.cshtml
@model FiresportCalendar.Models.Race
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <h2>Nový závod</h2>

    <form asp-action="Create" method="post">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label asp-for="Place" class="control-label"></label>
            <input asp-for="Place" class="form-control" />
            <span asp-validation-for="Place" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="DateTime" class="control-label"></label>
            <input asp-for="DateTime" class="form-control" type="datetime-local" value="@DateTime.Today.ToString("yyyy-MM-ddTHH:mm")" />
            <span asp-validation-for="DateTime" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Timer" class="control-label"></label>
            <input asp-for="Timer" class="form-check-input" type="checkbox" />
            <span asp-validation-for="Timer" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LeagueId" class="control-label"></label>
            <select asp-for="LeagueId" class="form-control" asp-items="@(new SelectList(ViewBag.Leagues, "Id", "Name"))">
                <option value="">Žádná liga</option>
            </select>
            <span asp-validation-for="LeagueId" class="text-danger"></span>
        </div>

        <div class="form-group mt-2">
            <input type="submit" value="Uložit" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Zrušit</a>
        </div>
    </form>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
}

FiresportCalendar/Views/Race/Edit.cshtml
@model FiresportCalendar.Models.Race
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <h2>Editace závodu</h2>

    <form asp-action="Edit" method="post">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label asp-for="Place" class="control-label"></label>
            <input asp-for="Place" class="form-control" />
            <span asp-validation-for="Place" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="DateTime" class="control-label"></label>
            <input asp-for="DateTime" class="form-control" type="datetime-local" />
            <span asp-validation-for="DateTime" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Timer" class="control-label"></label>
            <input asp-for="Timer" class="form-check-input" type="checkbox" />
            <span asp-validation-for="Timer" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LeagueId" class="control-label"></label>
            <select asp-for="LeagueId" class="form-control" asp-items="@(new SelectList(ViewBag.Leagues, "Id", "Name"))">
                <option value="">Žádná liga</option>
            </select>
            <span asp-validation-for="LeagueId" class="text-danger"></span>
        </div>

        <div class="form-group mt-2">
            <input type="submit" value="Uložit" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Zrušit</a>
        </div>
    </form>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
}

FiresportCalendar/Views/Race/Index.cshtml
@model List<Race>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="row">
        <div class="col-1" style="margin-top: 10px">
            <button class="mt-1 btn-sm btn-success" onclick="location.href='@Url.Action("Create", "Race")'">Přidat</button>
        </div>
    </div>
    @foreach (var race in Model)
    {
        var leagueNameLow = race.League?.Name.ToLower() ?? "non-league";

        <div id="@race.Id" class="row">
            <div class="col-8 mt-3">
                <div class="border-bottom rounded-3 text-white @leagueNameLow">
                    <h4 class="ms-2 pt-1">
                        @race.DateTime.ToString("d.M. HH:mm") @race?.League?.Name @race?.Place
                        @if (race.Timer)
                        {
                            <text> + Časomír</text>
                        }
                    </h4>
                </div>
            </div>
            <div class="container row col-4 mt-3">
                <div class="col-5" >
                    <button class="mt-1 btn-sm btn-warning" onclick="location.href='@Url.Action("Edit", "Race", new {id = race.Id})'">Upravit</button>
                </div>
                <div class="col-5">
                    <form asp-action="Delete" asp-controller="Race" method="post" onsubmit="return confirm('Opravdu chcete tento závod smazat?');">
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="id" value="@race.Id" />
                        <button type="submit" class="mt-1 btn-sm btn-danger">Odstranit</button>
                    </form>
                </div>
            </div>
        </div>
    }
}